# Generated by Django 2.2 on 2020-01-29 13:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenicate', '0002_myuser_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
